apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      volumes:
      - name: certs
        secret:
          secretName: hello-ssl-secret
      containers:
      - name: hello-world
        image: kdvolder/hello-world
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /certs
            name: certs
            readOnly: true
        env:
        - name: server.ssl.enabled
          value: "true"
        - name: server.ssl.key-alias
          value: "1"
        - name: server.ssl.keystore
          value: /certs/keystore.p12
        - name: server.ssl.key-store-password
          value: password
        - name: server.ssl.key-store-type
          value: PKCS12
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
  - port: 443
    targetPort: 8080
